name: ci

on:
  push:
    branches:
      - main
    paths-ignore:
      - "**.md"
      - "LICENSE"
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v4
      - run: go version
      - run: go install github.com/kyleconroy/sqlc/cmd/sqlc@main
      - run: sqlc version
      - run: sqlc generate
      - uses: actions/setup-node@v3
        with:
          node-version: 20
      - uses: pnpm/action-setup@v2
        with:
          version: 8
      - run: pnpm install
      - run: pnpm run test